%YAML:1.0

#common parameters
#support: 1 imu 2 cam,1 imu 1 cam;
imu: 1         
num_of_cam: 1  

imu_topic: "/camera2/imu"
image0_topic: "/t265/fisheye1/image_raw"
image1_topic: "/t265/fisheye1/image_raw"
gyr_topic : "/t265/gyro/sample"
acc_topic : "/t265/accel/sample"
output_path: "~/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
resolution: [848, 800] #读取这里的图片size,而不是相机calib里的

body_T_imu:
  cols: 4
  rows: 4
  data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

#imu parameters   continuous-time    
acc_n: 6.6952452471014112e-05           # accelerometer measurement noise continuous-time. 
acc_w: 9.9999997473787516e-05         # accelerometer bias random work noise continuous-time.
gyr_n: 5.1480301408446394e-06         # gyroscope measurement noise continuous-time.       
gyr_w: 4.9999999873762135e-07       # gyroscope bias random work noise continuous-time.     
g_norm: 9.81007     # gravity magnitude

loop_closure: 0                    # start loop closure
dbow3_voc_path: "/home/wya/ICE-BA_ws/src/ICE-BA/vocab/orbvoc.dbow3" 

#ground truth
show_GT: 0
GT_path: ""
GT_SKIP: 150 #刚开始就对齐的话对齐不好,稳定时对齐稍微好点

GBA_result_path: "/home/wya/odom_paper/ice-gba-vio.txt"
